// react/website/src/pages/admin/Contact.js
import React, { Component } from "react";

//components
import Textarea from "../../components/form/Textarea";
import Button from "../../components/form/Button";
import Form from "../../components/form/Form";
import Input from "../../components/form/Input";
import File from "../../components/form/File";

class About extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div id="admin-contact" className="container-fluid text-center bg-grey">
                <section className="section about">
                    <h2>Contact</h2>
                    <Form collection="contactElements" className="form">
                        <div className="row">
                            <div className="col-6 col-sm-6">
                                <Textarea className="input" name="content" placeholder="Content" />
                            </div>
                            <div className="col-6 col-sm-6">
                                <Input type="text" className="input" name="address" placeholder="Address" />
                            </div>
                            <div className="col-6 col-sm-6">
                                <Input type="text" className="input" name="phone" placeholder="Phone" />
                            </div>
                            <div className="col-6 col-sm-6">
                                <Input type="text" className="input" name="email" placeholder="Email" />
                            </div>
                            <div className="col-6 col-sm-6">
                                <File type="file" className="file" name="file" placeholder="File" />
                            </div>
                            <div className="col-12 col-sm-12">
                                <Button type="submit" className="btn btn-primary" text="Enviar"/>
                            </div>
                        </div>
                    </Form>
                </section>
            </div>
        )
    }
}
export default About;

// angular/website/src/app/contact/contact.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.css']
})
export class ContactComponent implements OnInit {

  constructor() {
    
  }

  ngOnInit() {

  }

}

<section class="section contact-form">
  <h1 class="title">Contact form</h1>
  <div class="row">
    <div class="col-lg-12">
      <form class="form" action="post">
        <label class="label" for="#name">Nome</label>
        <input type="text" class="input" id="name" required>
      
        <label class="label" for="#email">E-mail</label>
        <input type="text" class="input" id="email" required>
      
        <label class="label" for="#message">Mensagem</label>
        <textarea name="message"  class="textarea" id="message" required></textarea>

        <button class="button">
          <input class="input" type="submit">
          Enviar
        </button>
      </form>
    </div>
  </div>
</section>
